version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                USER_ID: $uid
                GROUP_ID: $gid
        image: php
        environment:
            XDEBUG_MODE: "debug"
            XDEBUG_SESSION: "PHPSTORM"
            PHP_IDE_CONFIG: "serverName=box"
            XDEBUG_CONFIG: "client_host=172.17.0.1 client_port=9003"
            SSH_AUTH_SOCK: "/ssh-agent"
        volumes:
            - ${HOME}/.composer:/.composer
            - ./:/var/www